### ISSUE TITLE
Deletion via Webhook not working

### ISSUE THREAD

**Issue by klickreflex** [jackabox/statamic-shopify#104]
I've setup Webhooks as in the docs (2022-01 latest), when I delete a product from Shopify it's not deleted from Statamic. Instead Horizon shows a failed Task:

```
Jackabox\Shopify\Jobs\FetchCollectionsForProductJob
ID
15ae5772-671c-4412-9913-c145180e546d
Queue
default
Attempts
3
Retries
0
Tags
Pushed At
2022-01-16 13:35:57
Failed At
2022-01-16 13:56:21
Exception
PHPShopify\Exception\ApiException: Not Found in /home/forge/stage.crazyceramic.klick.re/vendor/phpclassic/php-shopify/lib/ShopifyResource.php:559
Stack trace:
#0 /home/forge/stage.crazyceramic.klick.re/vendor/phpclassic/php-shopify/lib/ShopifyResource.php(347): PHPShopify\ShopifyResource->processResponse()
#1 /home/forge/stage.crazyceramic.klick.re/vendor/jackabox/statamic-shopify/src/Jobs/FetchCollectionsForProductJob.php(65): PHPShopify\ShopifyResource->get()
#2 /home/forge/stage.crazyceramic.klick.re/vendor/jackabox/statamic-shopify/src/Jobs/FetchCollectionsForProductJob.php(49): Jackabox\Shopify\Jobs\FetchCollectionsForProductJob->loopCollections()
Show All
```

**Comment by jackabox** [comment]
Hey, what do you mean 2022-01? The webhook should be set up as the add-on docs which specifies the end point to be posted too. 

How have you implemented these ?

**Comment by klickreflex** [comment]
Docs state it shoud be 'latest', Shopify shows 2022-1 prefix for 'latest' ('neueste' in german)
![image](https://user-images.githubusercontent.com/435825/149676710-9f107685-332c-4d15-b5fc-242ac87ccf42.png)

**Comment by klickreflex** [comment]
But maybe my problems are related to #95. Will have to check deletion with my current workaround next week.

**Comment by jackabox** [comment]
Try with 2021-07 and see if that fixes the issue. May be new changes in the latest updates.

**Comment by klickreflex** [comment]
Not sure with your message and https://github.com/jackabox/statamic-shopify/commit/1eade64e5dd857a839fbc3680e722d01d947d5f2: 

Should I still downgrade to api v2021-07 even when upgrading to 1.7?

**Comment by jackabox** [comment]
> Not sure with your message and [1eade64](https://github.com/jackabox/statamic-shopify/commit/1eade64e5dd857a839fbc3680e722d01d947d5f2):
> 
> Should I still downgrade to api v2021-07 even when upgrading to 1.7?

Nope, tested on latest version and all should be working fine :)

**Comment by klickreflex** [comment]
Awesome, thank you 🙏

**Comment by klickreflex** [comment]
Just after lauching I had to find out that deletion does not work after all.
It _seems_ like it worked because products disappeared from the backend, but the actual markdown files were kept (with only the id and blueprint being kept), causing for all sorts of issues in collection queries where they still appear as empty entries.

Here's how thoese files look like:

![image](https://user-images.githubusercontent.com/435825/150405295-84ae22e1-a862-41cd-b9a9-4727ad82c050.png)

**Comment by klickreflex** [comment]
I have to correct myself after investigating Git history. Deletion did work, but somehow those "ghost" files were automatically recreated (depending on the products days or hours) later:

<img width="1301" alt="CleanShot 2022-01-20 at 20 43 48@2x" src="https://user-images.githubusercontent.com/435825/150411034-4ea1f881-dcb5-4b7e-843b-eaee61ce2e9c.png">

Any ideas what could have caused this, and obviously how to prevent it in the future?

**Comment by jackabox** [comment]
@klickreflex There's nothing directly that would cause a ghost file to be created. Can you try to replicate it in your local environment also and let me know if it exists? If so I'll try and do a bit more debugging. However, I'm not getting ghost files in my test environments so not sure what's going on here. Although, I am not using git integration to recommit on file save.

**Comment by klickreflex** [comment]
I can't because I don't receive Webhooks locally and the site is live now.
